version: "3.3"
services:
    rabbit:
        image: rabbitmq:3.8-management-alpine
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - "/Users/mhung/Documents/Projects/RabbitMQdemo/rabbit:/var/lib/rabbitmq"
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
